/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file tar-module.h tar module header file */
/*
    Qore tar module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_TAR_MODULE_H
#define _QORE_TAR_MODULE_H

#include <qore/Qore.h>
#include <archive.h>
#include <archive_entry.h>

// Forward declarations
class QoreTarFile;

// Hashdecl init functions (generated by QPP from QC_TarFile.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_TarEntryInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_TarAddOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_TarExtractOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_TarCreateOptions(QoreNamespace& ns);

// Compression methods
#define TAR_CM_NONE     0   // No compression (.tar)
#define TAR_CM_GZIP     1   // Gzip compression (.tar.gz, .tgz)
#define TAR_CM_BZIP2    2   // Bzip2 compression (.tar.bz2)
#define TAR_CM_XZ       3   // XZ/LZMA compression (.tar.xz)
#define TAR_CM_ZSTD     4   // Zstandard compression (.tar.zst)
#define TAR_CM_LZ4      5   // LZ4 compression (.tar.lz4)

// Compression levels
#define TAR_COMPRESSION_DEFAULT -1
#define TAR_COMPRESSION_FASTEST 1
#define TAR_COMPRESSION_BEST    9

// Tar formats
#define TAR_FORMAT_USTAR    0   // POSIX.1-1988 ustar
#define TAR_FORMAT_PAX      1   // POSIX.1-2001 pax (default)
#define TAR_FORMAT_GNU      2   // GNU tar format
#define TAR_FORMAT_V7       3   // Old V7 tar

// Mode constants
enum TarMode {
    TAR_MODE_READ,
    TAR_MODE_WRITE,
    TAR_MODE_APPEND
};

// Global hashdecl pointers (initialized in tar-module.cpp)
extern const TypedHashDecl* hashdeclTarEntryInfo;
extern const TypedHashDecl* hashdeclTarAddOptions;
extern const TypedHashDecl* hashdeclTarExtractOptions;
extern const TypedHashDecl* hashdeclTarCreateOptions;

// Namespace
extern QoreNamespace TarNS;

// Helper function to get libarchive error message
DLLLOCAL const char* get_archive_error(struct archive* a);

// Helper function to convert compression method constant to libarchive filter
DLLLOCAL int compression_method_to_filter(int method);

// Helper function to convert format constant to libarchive format
DLLLOCAL int format_to_archive_format(int format);

// Helper function to detect compression from filename
DLLLOCAL int detect_compression_from_filename(const char* filename);

#endif // _QORE_TAR_MODULE_H
